In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [13]:
x=pd.read_csv('./Diabetes_XTrain.csv').values
y=pd.read_csv('./Diabetes_YTrain.csv').values

[[  7.    168.     88.    ...  38.2     0.787  40.   ]
 [  8.    110.     76.    ...  27.8     0.237  58.   ]
 [  7.    147.     76.    ...  39.4     0.257  43.   ]
 ...
 [  2.    122.     60.    ...  29.8     0.717  22.   ]
 [  4.    154.     72.    ...  31.3     0.338  37.   ]
 [  1.     88.     78.    ...  32.      0.365  29.   ]]


In [14]:
print(x.shape,y.shape)


(576, 8) (576, 1)


In [25]:
def dist(x1,x2):
    return np.sqrt(sum(x1-x2)**2)
def knn(x,y,querypoint,k=9):
    vals=[]
    m=x.shape[0]
    for i in range(m):
        d=dist(querypoint,x[i])
        vals.append((d,y[i]))
    vals=sorted(vals)
    # nearest/first k points
    vals=vals[:k]
    vals=np.array(vals)
    new_vals=np.unique(vals[:,1],return_counts=True)
    #print(new_vals)
    max_freq_index=new_vals[1].argmax()
    pred=new_vals[0][max_freq_index]
    return pred


In [26]:
x_test=pd.read_csv('./Diabetes_Xtest.csv')
#knn(x,y,query_x)

In [27]:
x_test=x_test.values

In [28]:
print(x_test,x_test.shape)

[[0.00e+00 1.80e+02 9.00e+01 ... 3.65e+01 3.14e-01 3.50e+01]
 [2.00e+00 9.30e+01 6.40e+01 ... 3.80e+01 6.74e-01 2.30e+01]
 [2.00e+00 1.14e+02 6.80e+01 ... 2.87e+01 9.20e-02 2.50e+01]
 ...
 [0.00e+00 1.62e+02 7.60e+01 ... 4.96e+01 3.64e-01 2.60e+01]
 [1.20e+01 8.40e+01 7.20e+01 ... 2.97e+01 2.97e-01 4.60e+01]
 [0.00e+00 9.40e+01 0.00e+00 ... 0.00e+00 2.56e-01 2.50e+01]] (192, 8)


In [32]:
y_test=[]
for i in range(x_test.shape[0]):
    y_test.append(knn(x,y,x_test[i],100))
    

In [33]:
df=pd.DataFrame(data=y_test,columns=["outcome"])
#df.insert(loc=0, column='Id', value=np.arange(len(df)))
df.to_csv('diabetes_y1_prediction.csv',index=False)
